# Finnish translations for PROJECT.
# Copyright (C) 2023 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2023.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2023-11-16 10:16+0200\n"
"PO-Revision-Date: 2023-11-16 10:21+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: fi\n"
"Language-Team: fi <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.13.1\n"

#: templates/base.html:12
msgid "SAR App"
msgstr ""

#: templates/base.html:21
msgid "SAR records"
msgstr ""

#: templates/base.html:24
msgid "New record"
msgstr ""

#: templates/base.html:32
msgid "Logged in as:"
msgstr ""

#: templates/base.html:35
msgid "Logout"
msgstr ""

#: venv/lib/python3.9/site-packages/click/_termui_impl.py:518
msgid "{editor}: Editing failed"
msgstr ""

#: venv/lib/python3.9/site-packages/click/_termui_impl.py:522
msgid "{editor}: Editing failed: {e}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:1120
msgid "Aborted!"
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:1309
#: venv/lib/python3.9/site-packages/click/decorators.py:559
msgid "Show this message and exit."
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:1340
#: venv/lib/python3.9/site-packages/click/core.py:1370
msgid "(Deprecated) {text}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:1387
msgid "Options"
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:1415
msgid "Got unexpected extra argument ({args})"
msgid_plural "Got unexpected extra arguments ({args})"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/click/core.py:1428
msgid "DeprecationWarning: The command {name!r} is deprecated."
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:1636
msgid "Commands"
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:1668
msgid "Missing command."
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:1746
msgid "No such command {name!r}."
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:2310
msgid "Value must be an iterable."
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:2333
msgid "Takes {nargs} values but 1 was given."
msgid_plural "Takes {nargs} values but {len} were given."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/click/core.py:2778
msgid "env var: {var}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:2808
msgid "(dynamic)"
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:2821
msgid "default: {default}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/core.py:2834
msgid "required"
msgstr ""

#: venv/lib/python3.9/site-packages/click/decorators.py:465
#, python-format
msgid "%(prog)s, version %(version)s"
msgstr ""

#: venv/lib/python3.9/site-packages/click/decorators.py:528
msgid "Show the version and exit."
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:44
#: venv/lib/python3.9/site-packages/click/exceptions.py:80
msgid "Error: {message}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:72
msgid "Try '{command} {option}' for help."
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:121
msgid "Invalid value: {message}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:123
msgid "Invalid value for {param_hint}: {message}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:179
msgid "Missing argument"
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:181
msgid "Missing option"
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:183
msgid "Missing parameter"
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:185
msgid "Missing {param_type}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:192
msgid "Missing parameter: {param_name}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:212
msgid "No such option: {name}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:226
msgid "Did you mean {possibility}?"
msgid_plural "(Possible options: {possibilities})"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:262
msgid "unknown error"
msgstr ""

#: venv/lib/python3.9/site-packages/click/exceptions.py:269
msgid "Could not open file {filename!r}: {message}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/parser.py:231
msgid "Argument {name!r} takes {nargs} values."
msgstr ""

#: venv/lib/python3.9/site-packages/click/parser.py:413
msgid "Option {name!r} does not take a value."
msgstr ""

#: venv/lib/python3.9/site-packages/click/parser.py:473
msgid "Option {name!r} requires an argument."
msgid_plural "Option {name!r} requires {nargs} arguments."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/click/shell_completion.py:318
msgid "Shell completion is not supported for Bash versions older than 4.4."
msgstr ""

#: venv/lib/python3.9/site-packages/click/shell_completion.py:326
msgid "Couldn't detect Bash version, shell completion is not supported."
msgstr ""

#: venv/lib/python3.9/site-packages/click/termui.py:158
msgid "Repeat for confirmation"
msgstr ""

#: venv/lib/python3.9/site-packages/click/termui.py:174
msgid "Error: The value you entered was invalid."
msgstr ""

#: venv/lib/python3.9/site-packages/click/termui.py:176
msgid "Error: {e.message}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/termui.py:187
msgid "Error: The two entered values do not match."
msgstr ""

#: venv/lib/python3.9/site-packages/click/termui.py:243
msgid "Error: invalid input"
msgstr ""

#: venv/lib/python3.9/site-packages/click/termui.py:773
msgid "Press any key to continue..."
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:266
msgid ""
"Choose from:\n"
"\t{choices}"
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:300
msgid "{value!r} is not {choice}."
msgid_plural "{value!r} is not one of {choices}."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/click/types.py:394
msgid "{value!r} does not match the format {format}."
msgid_plural "{value!r} does not match the formats {formats}."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/click/types.py:414
msgid "{value!r} is not a valid {number_type}."
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:470
msgid "{value} is not in the range {range}."
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:611
msgid "{value!r} is not a valid boolean."
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:635
msgid "{value!r} is not a valid UUID."
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:822
msgid "file"
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:824
msgid "directory"
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:826
msgid "path"
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:877
msgid "{name} {filename!r} does not exist."
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:886
msgid "{name} {filename!r} is a file."
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:894
msgid "{name} '{filename}' is a directory."
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:903
msgid "{name} {filename!r} is not readable."
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:912
msgid "{name} {filename!r} is not writable."
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:921
msgid "{name} {filename!r} is not executable."
msgstr ""

#: venv/lib/python3.9/site-packages/click/types.py:987
msgid "{len_type} values are required, but {len_value} was given."
msgid_plural "{len_type} values are required, but {len_value} were given."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/rediscli.py:113
msgid "Cli: Invalid command."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:374
msgid "File required."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:379
msgid "Invalid file type."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:404
msgid "Invalid name"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:774
#, python-format
msgid "File \"%(name)s\" already exists."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:819
#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:916
#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:978
#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1031
#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1078
#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1130
#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2290
msgid "Permission denied."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:912
msgid "File uploading is disabled."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:923
#, python-format
msgid "Successfully saved file: %(name)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:927
#, python-format
msgid "Failed to save file: %(error)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:935
msgid "Upload File"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:974
msgid "Directory creation is disabled."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:987
#, python-format
msgid "Successfully created directory: %(directory)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:991
#, python-format
msgid "Failed to create directory: %(error)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1001
msgid "Create Directory"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1027
msgid "Deletion is disabled."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1036
msgid "Directory deletion is disabled."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1042
#, python-format
msgid "Directory \"%(path)s\" was successfully deleted."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1044
#, python-format
msgid "Failed to delete directory: %(error)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1050
#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1205
#, python-format
msgid "File \"%(name)s\" was successfully deleted."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1052
#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1207
#, python-format
msgid "Failed to delete file: %(name)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1074
msgid "Renaming is disabled."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1082
msgid "Path does not exist."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1092
#, python-format
msgid "Successfully renamed \"%(src)s\" to \"%(dst)s\""
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1095
#, python-format
msgid "Failed to rename: %(error)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1109
#, python-format
msgid "Rename %(name)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1145
#, python-format
msgid "Error saving changes to %(name)s."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1149
#, python-format
msgid "Changes to %(name)s saved successfully."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1157
#, python-format
msgid "Error reading %(name)s."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1160
#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1169
#, python-format
msgid "Unexpected error while reading from %(name)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1166
#, python-format
msgid "Cannot edit %(name)s."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1184
#, python-format
msgid "Editing %(path)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/__init__.py:1196
msgid "File deletion is disabled."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/fileadmin/s3.py:156
msgid "Cannot operate on non empty directories"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/mongoengine/view.py:559
#, python-format
msgid "Failed to get model. %(error)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/mongoengine/view.py:578
#: venv/lib/python3.9/site-packages/flask_admin/contrib/peewee/view.py:462
#: venv/lib/python3.9/site-packages/flask_admin/contrib/pymongo/view.py:317
#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/view.py:1166
#, python-format
msgid "Failed to create record. %(error)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/mongoengine/view.py:604
#: venv/lib/python3.9/site-packages/flask_admin/contrib/peewee/view.py:481
#: venv/lib/python3.9/site-packages/flask_admin/contrib/pymongo/view.py:342
#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/view.py:1192
#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2427
#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2435
#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2437
#, python-format
msgid "Failed to update record. %(error)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/mongoengine/view.py:627
#: venv/lib/python3.9/site-packages/flask_admin/contrib/peewee/view.py:496
#: venv/lib/python3.9/site-packages/flask_admin/contrib/pymongo/view.py:367
#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/view.py:1217
#, python-format
msgid "Failed to delete record. %(error)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/mongoengine/view.py:676
#: venv/lib/python3.9/site-packages/flask_admin/contrib/peewee/view.py:532
#: venv/lib/python3.9/site-packages/flask_admin/contrib/pymongo/view.py:396
#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/view.py:1254
#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2238
#, python-format
msgid "Record was successfully deleted."
msgid_plural "%(count)s records were successfully deleted."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/mongoengine/view.py:682
#: venv/lib/python3.9/site-packages/flask_admin/contrib/peewee/view.py:538
#: venv/lib/python3.9/site-packages/flask_admin/contrib/pymongo/view.py:401
#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/view.py:1262
#, python-format
msgid "Failed to delete records. %(error)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/fields.py:127
#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/fields.py:177
#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/fields.py:182
#: venv/lib/python3.9/site-packages/flask_admin/model/fields.py:178
#: venv/lib/python3.9/site-packages/flask_admin/model/fields.py:227
msgid "Not a valid choice"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/validators.py:44
msgid "Already exists."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/validators.py:63
#, python-format
msgid "At least %(num)d item is required"
msgid_plural "At least %(num)d items are required"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/validators.py:79
msgid "Not a valid ISO currency code (e.g. USD, EUR, CNY)."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/validators.py:87
msgid "Not a valid color (e.g. \"red\", \"#f00\", \"#ff0000\")."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/view.py:1130
#, python-format
msgid "Integrity error. %(message)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/form/fields.py:98
msgid "Invalid time format"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/form/fields.py:147
msgid "Invalid Choice: could not coerce"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/form/fields.py:221
msgid "Invalid JSON"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/form/upload.py:213
msgid "Invalid file extension"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/form/upload.py:220
#: venv/lib/python3.9/site-packages/flask_admin/form/upload.py:290
#, python-format
msgid "File \"%s\" already exists."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/form/validators.py:16
msgid "This field requires at least one item."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:1702
msgid "There are no items in the table."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:1711
#, python-format
msgid "Invalid Filter Value: %(value)s"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2102
msgid "Record was successfully created."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2146
#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2198
#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2231
#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2419
msgid "Record does not exist."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2155
#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2423
msgid "Record was successfully saved."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2344
msgid "Tablib dependency not installed."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/base.py:2371
#, python-format
msgid "Export type \"%(type)s not supported."
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/template.py:79
#: venv/lib/python3.9/site-packages/flask_admin/model/template.py:86
msgid "View Record"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/template.py:93
#: venv/lib/python3.9/site-packages/flask_admin/model/template.py:100
msgid "Edit Record"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/template.py:107
msgid "Delete Record"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/widgets.py:62
msgid "Please select model"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/widgets.py:116
msgid "No"
msgstr ""

#: venv/lib/python3.9/site-packages/flask_admin/model/widgets.py:117
msgid "Yes"
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:86
#, python-format
msgid "Invalid field name '%s'."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:99
#, python-format
msgid "Field must be equal to %(other_name)s."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:145
#, python-format
msgid "Field must be at least %(min)d character long."
msgid_plural "Field must be at least %(min)d characters long."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:151
#, python-format
msgid "Field cannot be longer than %(max)d character."
msgid_plural "Field cannot be longer than %(max)d characters."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:157
#, python-format
msgid "Field must be exactly %(max)d character long."
msgid_plural "Field must be exactly %(max)d characters long."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:163
#, python-format
msgid "Field must be between %(min)d and %(max)d characters long."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:216
#, python-format
msgid "Number must be at least %(min)s."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:219
#, python-format
msgid "Number must be at most %(max)s."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:222
#, python-format
msgid "Number must be between %(min)s and %(max)s."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:293
#: venv/lib/python3.9/site-packages/wtforms/validators.py:323
msgid "This field is required."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:358
msgid "Invalid input."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:422
msgid "Invalid email address."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:460
msgid "Invalid IP address."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:503
msgid "Invalid Mac address."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:540
msgid "Invalid URL."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:561
msgid "Invalid UUID."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:594
#, python-format
msgid "Invalid value, must be one of: %(values)s."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:629
#, python-format
msgid "Invalid value, can't be any of: %(values)s."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:698
msgid "This field cannot be edited"
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/validators.py:714
msgid "This field is disabled and cannot have a value"
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/csrf/core.py:96
msgid "Invalid CSRF Token."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/csrf/session.py:63
msgid "CSRF token missing."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/csrf/session.py:71
msgid "CSRF failed."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/csrf/session.py:76
msgid "CSRF token expired."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/fields/choices.py:141
msgid "Invalid Choice: could not coerce."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/fields/choices.py:148
#: venv/lib/python3.9/site-packages/wtforms/fields/choices.py:202
msgid "Choices cannot be None."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/fields/choices.py:154
msgid "Not a valid choice."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/fields/choices.py:192
msgid "Invalid choice(s): one or more data inputs could not be coerced."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/fields/choices.py:211
#, python-format
msgid "'%(value)s' is not a valid choice for this field."
msgid_plural "'%(value)s' are not valid choices for this field."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.9/site-packages/wtforms/fields/datetime.py:51
msgid "Not a valid datetime value."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/fields/datetime.py:77
msgid "Not a valid date value."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/fields/datetime.py:103
msgid "Not a valid time value."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/fields/datetime.py:148
msgid "Not a valid week value."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/fields/numeric.py:82
#: venv/lib/python3.9/site-packages/wtforms/fields/numeric.py:92
msgid "Not a valid integer value."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/fields/numeric.py:168
msgid "Not a valid decimal value."
msgstr ""

#: venv/lib/python3.9/site-packages/wtforms/fields/numeric.py:197
msgid "Not a valid float value."
msgstr ""

